name: Deploy to cPanel

on:
  push:
    branches: [dev]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install dependencies
      working-directory: ./frontdecon
      run: npm install

    - name: Build project
      working-directory: ./frontdecon
      run: npm run build

    - name: Deploy via SFTP/SSH
      uses: easingthemes/sftp-deploy@v2.2.11
      with:
        server: ${{ secrets.CPANEL_HOST }}
        username: ${{ secrets.CPANEL_USER }}
        ssh-private-key: ${{ secrets.CPANEL_SSH_PVT_KEY }}
        known-hosts: ${{ secrets.CPANEL_HOST_KEY }}
        local-path: "./frontdecon/dist/*"
        remote-path: "./public_html/betadecon.iverse.space/"
        delete-extra-files: true