name: Deploy to cPanel

on:
  push:
    branches: [dev]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install dependencies
      working-directory: ./frontdecon
      run: npm install

    - name: Build project
      working-directory: ./frontdecon
      run: npm run build

    - name: Deploy via SSH
      uses: easingthemes/ssh-deploy@v4.1.8
      with:
        SSH_PRIVATE_KEY: ${{ secrets.CPANEL_SSH_PVT_KEY }}
        REMOTE_HOST: ${{ secrets.CPANEL_HOST }}
        REMOTE_USER: ${{ secrets.CPANEL_USER }}
        SOURCE: "./frontdecon/dist/"
        TARGET: "./public_html/betadecon.iverse.space/"
        ARGS: "-rlgoDzvc -i --delete"